os: linux
dist: focal
language: node_js
env:
  - CXX="g++-8"
node_js:
  - "16"
  - "12"
  - "10"


addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - gcc-8
